# -*- coding: utf-8 -*-
"""Senhas.txt em donwloads na pasta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fYyEHut6ENQKMHIOMuyU83q1V_8pzSx
"""

## Salvando na pasta do computador

from google.colab import files
import os
from random import choice
import string
import re

def gerar_senha():
    senha_valida = False
    caracteres = string.ascii_letters + string.digits + string.punctuation

    while not senha_valida:
        senha_gerada = ''.join(choice(caracteres) for _ in range(12))
        if (len(senha_gerada) > 11 and
            re.search("[a-z]", senha_gerada) and
            re.search("[A-Z]", senha_gerada) and
            re.search("[0-9]", senha_gerada) and
            re.search("[!@#$%^&*()_+]", senha_gerada)):
            senha_valida = True
            return senha_gerada

senhas = []

for _ in range(200):
    senhas.append(gerar_senha())

# Criar o arquivo senhas.txt no diretório temporário do Colab
caminho_arquivo = '/content/senhas.txt'

with open(caminho_arquivo, 'w') as arquivo:
    for senha in senhas:
        arquivo.write(senha + '\n')

# Solicitar permissões para o usuário baixar o arquivo
files.download(caminho_arquivo)